[package]
name = "kaboom"
version = "1.0.0"
edition = "2021"
description = "Simple and Intuitive library for Next-Gen application exiting"
license = "CC-PDDC"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
